export { default as ProfileLogoutIcon } from "./logout.svg";
export { default as ProfileInfoIcon } from "./profile.svg";
export { default as ProfileOrderIcon } from "./order.svg";
export { default as ProfileLanguageIcon } from "./language.svg";
export { default as ProfileFamilyMemberIcon } from "./famil-member.svg";
export { default as ProfileEditImageIcon } from "./add.svg";
export { default as ProfileBackIcon } from "./back.svg";
export { default as ProfileNoFamilyIcon } from "./family.svg";
export { default as ProfileMoreIcon } from "./more.svg";
